
const state={opportunities:[],seeds:[],profiles:[],content:[],approvals:[],briefs:[],assets:[],receipts:[],metrics:[],feedback:[],events:[],research:[],farmer_profiles:[],post_machine:[]};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&','<':'<','>':'>','"':'"',"'":'&#039;'}[c]));
async function refresh(){const r=await fetch('/api/state');Object.assign(state,await r.json());render()}
function count(k){return state[k]?.length??0}
function render(){const view=document.querySelector('[data-view].active')?.dataset.view||'overview';
const titles={overview:['Authority Engine','Descubra, desenvolva e opere ativos próprios de autoridade.'],radar:['Opportunity Radar','Oportunidades pesquisadas antes de qualquer execução.'],seeds:['Influencer Seeds Creator','Compare arquétipos, funções e modelos de perfil.'],farmer:['Influencer Farmer','Desenvolva avatares de autoridade com identidade e guardrails.'],postmachine:['Post Machine','Produção editorial, aprovação e publicação assistida.']};
$('#title').textContent=titles[view][0];$('#subtitle').textContent=titles[view][1];$('#crumb').textContent='Portfolio / '+titles[view][0];
$('#view').innerHTML=views[view]();}
const views={overview:()=>`<div class="cards"><div class="card"><div class="eyebrow">Oportunidades</div><div class="metric">${count('opportunities')}</div><div class="muted">Radar</div></div><div class="card"><div class="eyebrow">Seeds</div><div class="metric">${count('seeds')}</div><div class="muted">opções de persona</div></div><div class="card"><div class="eyebrow">Avatars</div><div class="metric">${count('farmer_profiles')}</div><div class="muted">desenvolvidos</div></div><div class="card"><div class="eyebrow">Conteúdo</div><div class="metric">${count('post_machine')}</div><div class="muted">semanas geradas</div></div></div><div class="section"><h2>Pipeline de criação</h2><div class="flow"><div class="stage"><span class="eyebrow">01</span><strong>Opportunity Radar</strong></div><span class="arrow">→</span><div class="stage"><span class="eyebrow">02</span><strong>Influencer Seeds</strong></div><span class="arrow">→</span><div class="stage"><span class="eyebrow">03</span><strong>Influencer Farmer</strong></div><span class="arrow">→</span><div class="stage"><span class="eyebrow">04</span><strong>Post Machine</strong></div></div></div><div class="grid"><div class="section"><h2>Últimas oportunidades</h2>${oppRows(4)}</div><div class="section"><h2>Governança</h2><div class="list"><div class="row"><span>Publicação automática</span><span class="tag amber">bloqueada</span></div><div class="row"><span>Integrações externas</span><span class="tag amber">não configuradas</span></div><div class="row"><span>API local</span><span class="tag green">operacional</span></div></div></div></div>`,radar:()=>`<div class="section"><div class="top"><div><h2>Oportunidades</h2><span class="muted">Nada avança sem evidência e seleção humana.</span></div><div style="display:flex;gap:8px"><button class="btn primary" onclick="openModal()">+ Nova oportunidade</button><button class="btn" onclick="openResearchModal()">🔍 Pesquisa Profunda</button></div></div>${oppRows()}</div>`,seeds:()=>`<div class="section"><div class="top"><div><h2>Influencer Seeds</h2><span class="muted">Selecione uma pesquisa para gerar arquétipos.</span></div><select id="researchSelect" class="btn" style="max-width:300px"><option value="">Selecione pesquisa...</option>${state.research.filter(r=>r.status==='completed').map(r=>`<option value="${r.id}">${esc(r.research?.marketSize?.slice(0,50)||'Pesquisa')} - ${r.opportunityId}</option>`).join('')}</select></div><div class="section"><h2>Seeds Geradas</h2>${seedRows()}</div>`,farmer:()=>`<div class="section"><div class="top"><div><h2>Perfis Desenvolvidos</h2><span class="muted">Selecione uma seed para desenvolver o perfil completo.</span></div></div>${farmerRows()}</div>`,postmachine:()=>`<div class="section"><div class="top"><div><h2>Post Machine</h2><span class="muted">Gere conteúdo semanal para perfis aprovados.</span></div><button class="btn primary" onclick="openPMModal()">+ Gerar Semana</button></div>${pmRows()}</div>`};
function oppRows(n){const a=state.opportunities.slice(-n).reverse();return a.length?'<div class="list">'+a.map(o=>`<div class="pipeline-step"><div class="step-content"><h4>${esc(o.niche)} / ${esc(o.subniche)}</h4><p>${esc(o.audience)} · ${esc(o.problem)}</p></div><div class="step-actions"><span class="tag">${esc(o.status)}</span>${o.status==='candidate'?`<button class="btn" onclick="openResearchModal('${o.id}')">🔍 Pesquisar</button>`:''}</div></div>`).join('')+'</div>':'<div class="empty">Nenhuma oportunidade ainda.<br><button class="btn" style="margin-top:12px" onclick="openModal()">Criar primeira opção</button></div>'}
function seedRows(){const a=state.seeds;return a.length?'<div class="list">'+a.map(s=>`<div class="seed-card"><div class="seed-info"><h4>${esc(s.name)}</h4><div class="muted">${esc(s.archetype)} · ${esc(s.function?.slice(0,60)||'')}</div><div class="seed-traits">${s.traits?.map(t=>`<span class="trait">${esc(t)}</span>`).join('')||''}</div></div><div class="step-actions"><span class="tag ${s.status==='selected'?'green':s.status==='proposed'?'blue':'amber'}">${esc(s.status)}</span>${s.status==='proposed'?`<button class="btn" onclick="selectSeed('${s.id}')">Selecionar</button>`:s.status==='selected'?`<button class="btn primary" onclick="openFarmerModal('${s.id}')">Desenvolver</button>`:''}</div></div>`).join('')+'</div>':'<div class="empty">Nenhuma seed gerada. Gere a partir de uma pesquisa concluída.</div>'}
function farmerRows(){const a=state.farmer_profiles;return a.length?'<div class="list">'+a.map(p=>`<div class="profile-card"><div class="profile-header"><div><h3>${esc(p.name)}</h3><div class="muted">${esc(p.archetype)} · ${p.pillars?.length||0} pilares · ${p.formats?.length||0} formatos</div></div><span class="tag ${p.status==='approved'?'green':p.status==='review'?'blue':'amber'}">${esc(p.status)}</span></div><div class="profile-sections"><div class="profile-section"><h5>Pilares</h5><ul>${p.pillars?.map(t=>`<li>${esc(t)}</li>`).join('')||'<li class="muted">—</li>'}</ul></div><div class="profile-section"><h5>Formatos</h5><ul>${p.formats?.map(t=>`<li>${esc(t)}</li>`).join('')||'<li class="muted">—</li>'}</ul></div><div class="profile-section"><h5>Temas transversais</h5><ul>${p.crossCuttingThemes?.map(t=>`<li>${esc(t)}</li>`).join('')||'<li class="muted">—</li>'}</ul></div><div class="profile-section"><h5>Guardrails</h5><ul>${p.guardrails?.slice(0,4).map(t=>`<li>${esc(t)}</li>`).join('')||'<li class="muted">—</li>'}</ul></div></div><div class="step-actions" style="margin-top:16px"><span class="tag ${p.status==='approved'?'green':'blue'}">${esc(p.status)}</span>${p.status==='review'?`<button class="btn primary" onclick="approveProfile('${p.id}')">Aprovar</button>`:`<button class="btn" onclick="openPMModal('${p.id}')">Gerar Conteúdo</button>`}</div></div>`).join('')+'</div>':'<div class="empty">Nenhum perfil desenvolvido. Selecione uma seed no módulo Seeds.</div>'}
function pmRows(){const a=state.post_machine;return a.length?'<div class="list">'+a.map(p=>`<div class="pm-output"><h4>Semana ${p.week} · Perfil: ${p.profileId?.slice(0,8)}...</h4><div class="pm-section"><h5>Artigos (${p.blogArticles?.length||0})</h5>${p.blogArticles?.map(b=>`<div class="pm-item"><strong>${esc(b.title)}</strong><p>${esc(b.seo?.metaDescription?.slice(0,120)||'')}</p></div>`).join('')||'<p class="muted">—</p>'}</div><div class="pm-section"><h5>Vídeos (${p.videoScripts?.length||0})</h5>${p.videoScripts?.map(v=>`<div class="pm-item"><strong>${esc(v.title)}</strong><p>${esc(v.structure?.hook?.slice(0,100)||'')}</p></div>`).join('')||'<p class="muted">—</p>'}</div><div class="pm-section"><h5>Shorts (${p.shorts?.length||0})</h5>${p.shorts?.map(s=>`<div class="pm-item"><strong>${esc(s.title)}</strong><p>${esc(s.caption?.slice(0,100)||'')}</p></div>`).join('')||'<p class="muted">—</p>'}</div><div class="pm-section"><h5>Stories (${p.stories?.length||0})</h5>${p.stories?.map(s=>`<div class="pm-item"><strong>${esc(s.title)}</strong><p>${esc(s.cta?.slice(0,100)||'')}</p></div>`).join('')||'<p class="muted">—</p>'}</div></div>`).join('')+'</div>':'<div class="empty">Nenhuma semana gerada. Selecione um perfil aprovado.</div>'}
function openModal(oid=''){$('#modal').classList.remove('hidden');$('#oppForm').reset();$('#formStatus').textContent='';if(oid)$('#oppForm').querySelector('input[name=niche]').value=''}
function closeModal(){$('#modal').classList.add('hidden')}
function openResearchModal(oid=''){$('#modalResearch').classList.remove('hidden');$('#researchStatus').textContent='';$('#researchLoader').classList.add('hidden');if(oid)$('#modalResearch').querySelector('input[name=opportunityId]').value=oid}
function closeResearchModal(){$('#modalResearch').classList.add('hidden')}
function openSeedsModal(researchId){$('#modalSeeds').classList.remove('hidden');loadSeedsForResearch(researchId)}
function closeSeedsModal(){$('#modalSeeds').classList.add('hidden')}
function openFarmerModal(seedId){$('#modalFarmer').classList.remove('hidden');$('#farmerSeedId').value=seedId;$('#farmerStatus').textContent='';$('#farmerForm').reset()}
function closeFarmerModal(){$('#modalFarmer').classList.add('hidden')}
function openPMModal(profileId=''){$('#modalPostMachine').classList.remove('hidden');$('#pmStatus').textContent='';$('#pmLoader').classList.add('hidden');loadProfilesForPM();if(profileId)$('#pmProfileId').value=profileId}
function closePMModal(){$('#modalPostMachine').classList.add('hidden')}
async function loadSeedsForResearch(researchId){const r=await fetch('/api/seeds/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({researchId})});if(r.ok){const data=await r.json();render();openSeedsModal()}else{alert('Erro ao gerar seeds')}}
async function loadProfilesForPM(){const r=await fetch('/api/farmer/profiles');const profiles=await r.json();const sel=$('#pmProfileId');sel.innerHTML='<option value="">Selecione...</option>';profiles.filter(p=>p.status==='approved').forEach(p=>sel.innerHTML+=`<option value="${p.id}">${esc(p.name)} (${esc(p.archetype)})</option>`)}
async function selectSeed(seedId){const r=await fetch('/api/seeds/select',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({seedId})});if(r.ok){await refresh()}else{alert('Erro ao selecionar seed')}}
async function approveProfile(profileId){const r=await fetch('/api/farmer/profile/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({profileId})});if(r.ok){await refresh()}else{alert('Erro ao aprovar')}}
$('#newBtn').onclick=()=>openModal();
$('#cancel').onclick=closeModal;
$('#cancelResearch').onclick=closeResearchModal;
$('#cancelSeeds').onclick=closeSeedsModal;
$('#cancelFarmer').onclick=closeFarmerModal;
$('#cancelPM').onclick=closePMModal;
$('#runResearch').onclick=async()=>{const opportunityId=$('#modalResearch input[name=opportunityId]').value;if(!opportunityId){alert('Informe o ID');return}$('#runResearch').disabled=true;$('#researchLoader').classList.remove('hidden');$('#researchStatus').textContent='Executando pesquisa...';const r=await fetch('/api/opportunities/research',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({opportunityId})});if(r.ok){$('#researchStatus').textContent='Pesquisa concluída!';setTimeout(()=>{closeResearchModal();refresh()},1000)}else{const err=await r.json();$('#researchStatus').textContent='Erro: '+err.error}$('#runResearch').disabled=false;$('#researchLoader').classList.add('hidden')};
$('#oppForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const r=await fetch('/api/opportunities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});if(!r.ok){$('#formStatus').textContent='Não foi possível criar a opção.';return}closeModal();await refresh()};
$('#farmerForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const themes=data.themes?data.themes.split('\n').map(t=>t.trim()).filter(Boolean):[];const r=await fetch('/api/farmer/profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({seedId:data.seedId,selectedThemes:themes})});if(!r.ok){$('#farmerStatus').textContent='Erro ao desenvolver perfil';return}closeFarmerModal();await refresh()};
$('#pmForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const week=parseInt(data.week)||1;$('runPM').disabled=true;$('#pmLoader').classList.remove('hidden');$('#pmStatus').textContent='Gerando conteúdo...';const r=await fetch('/api/post-machine/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({profileId:data.profileId,week})});if(r.ok){$('#pmStatus').textContent='Conteúdo gerado!';setTimeout(()=>{closePMModal();refresh()},1000)}else{const err=await r.json();$('#pmStatus').textContent='Erro: '+err.error}$('runPM').disabled=false;$('#pmLoader').classList.add('hidden')};
$('#nav').onclick=e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()};
refresh();
