import test from 'node:test';
import assert from 'node:assert/strict';
import { FakeMarketplaceAdapter, createOpportunity } from '../opportunity-radar.js';
import { createSeeds, selectSeed } from '../influencer-seeds.js';
import { farmProfile, validatePersonaForReview } from '../influencer-farmer.js';
import { adaptDraft, createRadarFeedback, createVersion, enqueueBrief, FakePublishingAdapter, produceDraft, publishAssisted, recordMetrics, requestHumanApproval, submitForReview } from '../post-machine.js';

async function fixture() {
  const opportunity = await createOpportunity(new FakeMarketplaceAdapter(), { niche: 'business displays', subniche: 'trade show lighting', problem: 'small businesses need their booth to be visible in a crowded aisle', audience: 'small business exhibitors' });
  const seed = selectSeed(createSeeds(opportunity), `seed_${opportunity.id}_curator`);
  return { opportunity, profile: { ...farmProfile(seed), status: 'approved' as const } };
}
function brief(profile: Awaited<ReturnType<typeof fixture>>['profile'], source = true) { return { id: 'b1', profileId: profile.id, topic: 'trade show lighting', pillar: profile.pillars[0]!, format: profile.formats[0]!, channel: 'short-video', objective: 'help choose', sources: source ? [{ source: 'fake://source', accessedAt: new Date().toISOString(), observation: 'fixture evidence', kind: 'fact' as const }] : [], status: 'draft' as const }; }

test('PMA-001 enfileira briefing válido e bloqueia entrada sem fonte/guardrail', async () => { const { profile } = await fixture(); const queued = enqueueBrief(profile, brief(profile)); assert.equal(queued.state, 'draft'); assert.equal(queued.brief.owner, 'editorial-operator'); assert.equal(queued.brief.nextGate, 'produce_draft'); const blocked = enqueueBrief(profile, brief(profile, false)); assert.equal(blocked.state, 'blocked'); assert.ok(blocked.reasons.includes('sources_required')); });
test('PMA-002 produz draft na voz, preserva fontes/disclosure e falha em claim proibido', async () => { const { profile } = await fixture(); const draft = produceDraft(profile, brief(profile)); assert.equal(draft.status, 'draft'); assert.match(draft.body, /trade show lighting/); assert.match(draft.disclosure!, /inteligência artificial/); assert.equal(draft.sources?.length, 1); const unsafe = { ...brief(profile), topic: 'cura garantida' }; assert.throws(() => produceDraft(profile, unsafe), /prohibited_claim|invented_testimonial/); });
test('PMA-003 adapta por canal e versiona assets com fontes e disclosure', async () => { const { profile } = await fixture(); const draft = { ...produceDraft(profile, brief(profile)), id: 'd1' }; const asset = adaptDraft(draft, 'short-video'); assert.equal(asset.name, 'AE_b1_short-video_v01'); assert.match(asset.content, /inteligência artificial/); assert.equal(asset.sources.length, 1); assert.equal(createVersion(draft, 'short-video', 2).version, 'v02'); assert.throws(() => adaptDraft(draft, 'unknown'), /unsupported_channel/); });
test('PMA-004 exige revisão, aprovação específica e receipt fake; sem aprovação falha fechado', async () => { const { profile } = await fixture(); const draft = { ...produceDraft(profile, brief(profile)), id: 'd1' }; const awaiting = requestHumanApproval(submitForReview(draft)); assert.equal(awaiting.status, 'awaiting_human_approval'); await assert.rejects(() => publishAssisted(awaiting, undefined, new FakePublishingAdapter()), /specific_publication_approval_required/); const approval = { id: 'a1', targetId: 'd1', targetVersion: 'v01', channel: 'short-video', scope: 'publication' as const, approved: true as const, approver: 'Sergio', approvedAt: new Date().toISOString() }; const receipt = await publishAssisted(awaiting, approval, new FakePublishingAdapter()); assert.equal(receipt.mode, 'fake'); assert.equal(receipt.version, 'v01'); });
test('PMA-005 registra métricas separadas e feedback honesto ao Radar', async () => { const metric = recordMetrics({ briefId: 'b1', draftId: 'd1', version: 'v01', channel: 'short-video', period: { from: '2026-01-01', to: '2026-01-07' }, source: 'fake://metrics', attention: { views: 10, saves: 2, shares: 1 }, trust: { comments: 3 }, traffic: { clicks: 1, ctr: 0.1 }, leads: { count: 0 }, conversion: { count: 0 }, sufficient: false, limitation: 'fixture sem amostra real' }); const feedback = createRadarFeedback(metric); assert.ok(feedback.signals.includes('insufficient_data')); assert.match(feedback.recommendation, /Não concluir/); assert.equal(metric.conversion.count, 0); });
test('pipeline S3→S4 aceita apenas perfil aprovado', async () => { const { opportunity, profile } = await fixture(); assert.equal(opportunity.status, 'qualified'); assert.equal(validatePersonaForReview(profile).valid, true); const blocked = enqueueBrief({ ...profile, status: 'review' }, brief(profile)); assert.equal(blocked.state, 'blocked'); assert.ok(blocked.reasons.includes('profile_not_approved')); });
