export type EvidenceKind = 'fact' | 'hypothesis' | 'recommendation' | 'risk' | 'blocker';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';
export interface RuntimeOwned { ownerId?: string; createdBy?: string; }
export interface Evidence { source: string; accessedAt: string; observation: string; kind: EvidenceKind; limitation?: string | undefined; }
export interface MarketplaceSource { name: string; endpoint: string; version: string; scope: string; configured: boolean; credentialStatus: 'configured' | 'missing' | 'expired' | 'unknown'; checkedAt: string; limitation: string; }
export type Availability = 'in_stock' | 'out_of_stock' | 'unknown';
export interface MarketplaceProduct { id: string; sourceRecordId?: string; marketplace: string; title: string; category: string; niche: string; subniche: string; price?: number; currency?: string; availability: Availability; observedAt: string; evidence: Evidence[]; }
export interface TrendObservation { niche: string; subniche: string; query: string; strength: number; observedAt: string; source: string; }
export interface TrendSignal { id: string; niche: string; subniche: string; query: string; strength: number; period: string; evidence: Evidence[]; status?: 'observed' | 'insufficient_evidence'; }
export interface MarketplaceSearchResult { products: MarketplaceProduct[]; trends: TrendSignal[]; sources?: MarketplaceSource[]; }
export interface MarketplaceAdapter { name: string; source: MarketplaceSource; search(input: { niche: string; subniche?: string }): Promise<MarketplaceSearchResult>; }
export interface ScoreFactor { value: number; definition: string; justification: string; }
export interface ScoreFactors { demand: ScoreFactor; intent: ScoreFactor; content: ScoreFactor; productFit: ScoreFactor; authority: ScoreFactor; risk: ScoreFactor; confidence: ScoreFactor; }
export interface OpportunityScores { demand: number; intent: number; content: number; productFit: number; authority: number; risk: number; confidence: number; total: number; factors: ScoreFactors; version: string; }
export interface Opportunity { id: string; niche: string; subniche: string; problem: string; audience: string; products: MarketplaceProduct[]; trends: TrendSignal[]; scores: OpportunityScores; risks: string[]; blockers: string[]; evidence: Evidence[]; status: 'candidate' | 'qualified' | 'blocked'; }
export interface OpportunityDossier { id: string; opportunity: Opportunity; generatedAt: string; recommendation: 'advance' | 'advance_with_constraints' | 'review' | 'block'; facts: Evidence[]; hypotheses: Evidence[]; recommendations: Evidence[]; risks: Evidence[]; blockers: Evidence[]; freeAlternatives: string[]; pendingDecision: string; handoff: { target: 'influencer-seeds-creator'; ready: boolean; inputs: string[] }; }
export interface ReferenceComparison { reference: string; proximity: number; differences: string[]; limitation: string; }
export interface ScoreBreakdown { authority: number; audience: number; differentiation: number; content: number; compliance: number; viability: number; riskPenalty: number; total: number; rationale: Record<string, string>; }
export type SeedStatus = 'proposed' | 'selected' | 'blocked' | 'invalid';
export interface InfluencerSeed { id: string; opportunityId: string; name: string; archetype: string; archetypeKey: string; taxonomyVersion: string; function: string; editorialFunctionCount: number; mentorRole: 'mentor'; audience: string; problem: string; thesis: string; promise: string; traits: string[]; decisionCompass: string; not: string[]; backstory: string; differentiation: string; voice: string; visualDirection: string; anchorFace: string; signatureTrait: string; formats: string[]; monetizationPaths: string[]; risks: string[]; antiNetwork: string[]; rationale?: string; roundness?: string[]; differentiationMatrix: ReferenceComparison[]; scoreBreakdown: ScoreBreakdown; score: number; status: SeedStatus; }
export interface SeedComparisonPackage { opportunityId: string; taxonomyVersion: string; generatedAt: string; alternatives: InfluencerSeed[]; recommendation: { seedId: string | null; rationale: string; argumentsAgainst: Record<string, string[]> }; openQuestions: string[]; decision: 'pending_human_selection' | 'selected' | 'reject_all'; handoffToS3: InfluencerSeed | null; }
export interface CharacterBible { version: string; staticCore: { mentorRole: 'mentor'; readerIsProtagonist: boolean; thesis: string; promise: string; values: string[]; tensions: string[]; compass: string; not: string[]; backstory: string; }; dynamicSurface: { currentTopics: string[]; allowedAdaptations: string[]; invariantRules: string[] }; voice: { tone: string; rhythm: string; vocabulary: string[]; humor: string; preferredPhrases: string[]; prohibitedPhrases: string[]; assertiveness: string; cta: string }; appearance: { apparentAge: string; features: string; wardrobe: string; scenarios: string[]; lighting: string; palette: string; recurringElements: string[]; prohibitedElements: string[]; facialAnchor: string; signatureTrait: string }; prompts: { base: string; context: string[]; negative: string[] }; aiDisclosure: { label: string; placement: string; aboutText: string }; }
export interface ClaimRule { claim: string; class: 'allowed' | 'soften' | 'prohibited'; source: string; asOf: string; limitation: string; review: string; }
export interface EditorialFormat { name: string; audienceInput: string; valueDelivery: string; cta: string; journeyStage: string; }
export interface EditorialPlan { ninetyDays: { days1to30: string; days31to60: string; days61to90: string; cadence: string }; topics: string[]; formats: EditorialFormat[]; ownAsset: string; }
export interface MonetizationHypothesis { primary: string; secondary: string[]; naturalMoment: string; freeValue: string; honestTest: string; risks: string[]; }
export interface VisualAssetProvider { name: string; configured: boolean; generate(input: { profileId: string; prompt: string }): Promise<{ assetId: string; uri: string }>; }
export interface FluxHandoff { id: string; version: string; status: string; decisionRequired: string; optionVsProject: string; input: Record<string, string>; done: string[]; artifacts: string[]; risks: string[]; hypotheses: string[]; metrics: string[]; owner: string; next: { agent: string; task: string; gate: string }; evidence: string[]; }
export interface Profile { id: string; seedId: string; name: string; brand: string; bio: string; disclosure: string; thesis: string; promise: string; mentorRole: 'mentor'; archetype: string; traits: string[]; decisionCompass: string; not: string[]; backstory: string; authorityMethod: string; voice: { tone: string; vocabulary: string[]; prohibited: string[] }; visual: { style: string; palette: string; continuity: string; anchorFace: string; signatureTrait: string; prompts: string[] }; pillars: string[]; formats: string[]; guardrails: string[]; claims: { allowed: string[]; soften: string[]; prohibited: string[] }; aboutPage: string; footerDisclaimer: string; monetizationModel: string[]; status: 'development' | 'review' | 'approved'; characterBible: CharacterBible; claimMatrix: ClaimRule[]; editorialPlan: EditorialPlan; monetizationHypothesis: MonetizationHypothesis; }
export type EditorialState = 'draft' | 'review' | 'awaiting_human_approval' | 'published' | 'blocked';
export interface ContentBrief { id: string; profileId: string; topic: string; pillar: string; format: string; channel: string; objective: string; product?: string; sources: Evidence[]; owner?: string; priority?: 'low' | 'medium' | 'high'; nextGate?: string; approvedAt?: string; status: EditorialState; }
export interface AssetSource { source: string; license: string; attribution?: string; }
export interface AssetVersion { id: string; briefId: string; parentId?: string | undefined; channel: string; version: string; name: string; kind: 'copy' | 'image' | 'video' | 'link'; content: string; specification: { maxCharacters?: number; format: string }; source?: AssetSource; disclosure: string; sources: Evidence[]; }
export interface ContentDraft extends RuntimeOwned { id?: string; briefId: string; title: string; body: string; caption: string; cta: string; disclosure?: string; sources?: Evidence[]; channel?: string; format?: string; assetIds?: string[]; version: string; status: EditorialState; }
export interface Approval extends RuntimeOwned { id: string; targetId: string; targetVersion: string; channel: string; scope: 'publication'; approved: true; approver: string; approvedAt: string; }
export interface PublicationReceipt { id: string; draftId: string; briefId: string; channel: string; version: string; provider: string; externalId: string; publishedAt: string; operator: string; mode: 'assisted' | 'fake'; }
export interface ChannelAdapter { name: string; publish(input: { draft: ContentDraft; channel: string; approval: Approval }): Promise<PublicationReceipt>; }
export interface MetricRecord { id: string; receiptId?: string; briefId: string; draftId?: string; version: string; channel: string; period: { from: string; to: string }; source: string; attention: { impressions?: number; views?: number; saves?: number; shares?: number }; trust: { comments?: number; positiveSignals?: number; negativeSignals?: number }; traffic: { clicks?: number; ctr?: number }; leads: { count?: number; quality?: string }; conversion: { count?: number; rate?: number; revenue?: number; currency?: string }; sufficient: boolean; limitation?: string; }
export interface RadarFeedback { id: string; metricId: string; briefId: string; signals: string[]; questions: string[]; recommendation: string; createdAt: string; }
