export type EvidenceKind = 'fact' | 'hypothesis' | 'recommendation' | 'risk' | 'blocker';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';

export interface Evidence { source: string; accessedAt: string; observation: string; limitation?: string; kind: EvidenceKind; }
export interface MarketplaceProduct { id: string; marketplace: string; title: string; category: string; niche: string; subniche: string; price?: number; currency?: string; availability: 'in_stock' | 'out_of_stock' | 'unknown'; observedAt: string; evidence: Evidence[]; }
export interface TrendSignal { id: string; niche: string; subniche: string; query: string; strength: number; period: string; evidence: Evidence[]; }
export interface Opportunity { id: string; niche: string; subniche: string; problem: string; audience: string; products: MarketplaceProduct[]; trends: TrendSignal[]; scores: { demand: number; intent: number; content: number; productFit: number; authority: number; risk: number; total: number }; risks: string[]; evidence: Evidence[]; status: 'candidate' | 'qualified' | 'blocked'; }
export interface InfluencerSeed { id: string; opportunityId: string; name: string; archetype: string; function: string; mentorRole: 'mentor'; audience: string; problem: string; thesis: string; promise: string; traits: string[]; decisionCompass: string; not: string[]; backstory: string; differentiation: string; voice: string; visualDirection: string; anchorFace: string; signatureTrait: string; formats: string[]; monetizationPaths: string[]; risks: string[]; antiNetwork: string[]; score: number; status: 'proposed' | 'selected' | 'blocked'; }
export interface Profile { id: string; seedId: string; name: string; brand: string; bio: string; disclosure: string; thesis: string; promise: string; mentorRole: 'mentor'; archetype: string; traits: string[]; decisionCompass: string; not: string[]; backstory: string; authorityMethod: string; voice: { tone: string; vocabulary: string[]; prohibited: string[] }; visual: { style: string; palette: string; continuity: string; anchorFace: string; signatureTrait: string; prompts: string[] }; pillars: string[]; formats: string[]; guardrails: string[]; claims: { allowed: string[]; soften: string[]; prohibited: string[] }; aboutPage: string; footerDisclaimer: string; monetizationModel: string[]; status: 'development' | 'review' | 'approved'; }
export interface ContentBrief { id: string; profileId: string; topic: string; pillar: string; format: string; channel: string; objective: string; product?: string; sources: Evidence[]; status: 'draft' | 'review' | 'awaiting_human_approval' | 'published' | 'blocked'; }
export interface ContentDraft { briefId: string; title: string; body: string; caption: string; cta: string; disclosure?: string; version: string; status: ContentBrief['status']; }

export interface MarketplaceAdapter { name: string; search(input: { niche: string; subniche?: string }): Promise<{ products: MarketplaceProduct[]; trends: TrendSignal[] }>; }
